### ISSUE TITLE
Getting the error while using it

### ISSUE THREAD

**Issue by Vishwastp89** [shahargl/upload-github-workflow-logs-to-elastic#2]
File "/usr/lib/python3.7/logging/config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.7/logging/config.py", line 712, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.7/logging/config.py", line 383, in resolve
    found = self.importer(used)
  File "/app/elastic_handler.py", line 49, in <module>
    scheme="https"
TypeError: __init__() got an unexpected keyword argument 'scheme'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    import logger
  File "/app/logger.py", line 41, in <module>
    logging.config.dictConfig(LOGGING_CONFIG)
  File "/usr/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'elastic'

**Comment by ghost** [comment]
+1

**Comment by sapanovych911** [comment]
+

**Comment by sapanovych911** [comment]
+1

**Comment by kennysphan** [comment]
+1

**Comment by kennysphan** [comment]
+1

**Comment by shahargl** [comment]
@sapanovych911 @kennysphan @Admir-Hadzic-MOP 
Hey thanks!
I'll look into it shortly and we make it work <3

**Comment by shahargl** [comment]
Fixed, can you maybe recheck? @sapanovych911 @kennysphan
